service: grow-ext-file-upload
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: numpy
  version: latest

handlers:
- url: /uploader.html
  static_files: uploader.html
  upload: uploader.html
  expiration: 1s
  secure: always
  login: admin
- url: .*
  script: main.app
