service: upload
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: numpy
  version: latest

#env_variables:
#  GROW_FILE_UPLOAD_BUCKET: bucket
#  GROW_FILE_UPLOAD_FOLDER: folder

handlers:
- url: /uploader.html
  static_files: uploader.html
  upload: uploader.html
  expiration: 1s
  login: admin
- url: /
  static_files: uploader.html
  upload: uploader.html
  expiration: 1s
  login: admin
- url: .*
  script: main.app
